Repository jenkins-x/jenkins-x-serverless-filerunner, pull requests merged in 2019-05, with the labels that each got.

#113 feat: using BUILD_NUMBER or BUILD_ID for tests
  jx/scripts/test.sh
Labels: approved, size/S

#115 fix: new version of git
  Dockerfile
Labels: approved, lgtm, size/S

#117 feat: updated skaffold to v0.29.0
  Dockerfile
Labels: approved, size/XS

#121 feat: updating to helm3 alpha1
  Dockerfile
Labels: approved, size/XS

#118 chore: updated jenkins to LTS 2.164.3
  Dockerfile
  jenkins-x.yml
  packager-config.yml
  pom.xml
Labels: approved, size/S

#124 chore: update to skaffold v0.30.0
  Dockerfile
Labels: approved, size/XS
